theme: jekyll-theme-tactile
title: __Miastox__ - Best stab city iNET
description: miastox walczy o pierwsze miejsce w rankingu najlepszych miast w sieci
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
